#server
server.port=8080

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/intellidoc_db
spring.datasource.username=intellidoc
spring.datasource.password=intellidoc123
spring.datasource.driver-class-name=org.postgresql.Driver

#jpa - hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Security (temporary - we'll replace with JWT in Week 2)
spring.security.user.name=admin
spring.security.user.password=admin